language: python
python:
  - "2.7"
# command to install dependencies
addons:
  apt:
    packages:
      - gfortran
      - libgfortran3
      - liblapack-dev
      - libatlas-dev
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda create --yes -q -n pyenv python=2.7 numpy=1.9.2 scipy=0.16.0 nose=1.3.7 sphinx=1.3
  - source activate pyenv
  - conda install --yes python=$TRAVIS_PYTHON_VERSION cython biopython matplotlib networkx
  - pip install package/
  - pip install testsuite/
  - pip install coveralls tempdir
  - chmod +x testsuite/MDAnalysisTests/mda_nosetests
# command to run tests
script:
  - ./testsuite/MDAnalysisTests/mda_nosetests -v --with-coverage --cover-package MDAnalysis --processes=2 --process-timeout=120 --with-memleak
  - |
     test ${TRAVIS_PULL_REQUEST} == "false" && \
     test ${TRAVIS_BRANCH} == ${GH_DOC_BRANCH} && \
     test "${TRAVIS_BUILD_NUMBER}.1" == "${TRAVIS_JOB_NUMBER}" && \
     (cd ./package && python setup.py build_ext --inplace) && \
     (cd ./package/doc/sphinx && make clean html) || \
     true
after_success:
  - coveralls
  - |
     test ${TRAVIS_PULL_REQUEST} == "false" && \
     test ${TRAVIS_BRANCH} == ${GH_DOC_BRANCH} && \
     test "${TRAVIS_BUILD_NUMBER}.1" == "${TRAVIS_JOB_NUMBER}" && \
     bash ./maintainer/deploy_docs.sh

env:
   global:
      - secure: "HIj3p+p2PV8DBVg/KGUx6n83KwB0ASE5FwOn0SMB9zxnzAqe8sapwdBQdMdq0sXB7xT1spJqRxuxOMVEVn35BNLu7bxMLfa4287C8YXcomnvmv9xruxAsjsIewnNQ80vtPVbQddBPxa4jKbqgPby5QhhAP8KANAqYe44pIV70fY="
      - GH_DOC_BRANCH: develop
      - GH_REPOSITORY: github.com/MDAnalysis/mdanalysis.git
      - GIT_CI_USER: TravisCI
      - GIT_CI_EMAIL: TravisCI@mdanalysis.org
      - MDA_DOCDIR: package/doc/html
